/********************************************************************
* mesFITDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mesFITDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemesFITDict();
extern void G__cpp_setup_inheritancemesFITDict();
extern void G__cpp_setup_typetablemesFITDict();
extern void G__cpp_setup_memvarmesFITDict();
extern void G__cpp_setup_globalmesFITDict();
extern void G__cpp_setup_memfuncmesFITDict();
extern void G__cpp_setup_funcmesFITDict();
extern void G__set_cpp_environmentmesFITDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "mesFIT.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mesFITDictLN_TClass;
extern G__linked_taginfo G__mesFITDictLN_TBuffer;
extern G__linked_taginfo G__mesFITDictLN_TMemberInspector;
extern G__linked_taginfo G__mesFITDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__mesFITDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mesFITDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__mesFITDictLN_TH1;
extern G__linked_taginfo G__mesFITDictLN_TF1;
extern G__linked_taginfo G__mesFITDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__mesFITDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__mesFITDictLN_TH1D;
extern G__linked_taginfo G__mesFITDictLN_TLatex;
extern G__linked_taginfo G__mesFITDictLN_mesFIT;

/* STUB derived class for protected member access */
