/********************************************************************
* PIDDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PIDDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablePIDDataDict();
extern void G__cpp_setup_inheritancePIDDataDict();
extern void G__cpp_setup_typetablePIDDataDict();
extern void G__cpp_setup_memvarPIDDataDict();
extern void G__cpp_setup_globalPIDDataDict();
extern void G__cpp_setup_memfuncPIDDataDict();
extern void G__cpp_setup_funcPIDDataDict();
extern void G__set_cpp_environmentPIDDataDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "PIDData.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PIDDataDictLN_TClass;
extern G__linked_taginfo G__PIDDataDictLN_TBuffer;
extern G__linked_taginfo G__PIDDataDictLN_TMemberInspector;
extern G__linked_taginfo G__PIDDataDictLN_TObject;
extern G__linked_taginfo G__PIDDataDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__PIDDataDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PIDDataDictLN_PIDData;

/* STUB derived class for protected member access */
