/********************************************************************
* PIDTableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PIDTableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablePIDTableDict();
extern void G__cpp_setup_inheritancePIDTableDict();
extern void G__cpp_setup_typetablePIDTableDict();
extern void G__cpp_setup_memvarPIDTableDict();
extern void G__cpp_setup_globalPIDTableDict();
extern void G__cpp_setup_memfuncPIDTableDict();
extern void G__cpp_setup_funcPIDTableDict();
extern void G__set_cpp_environmentPIDTableDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "PIDTable.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PIDTableDictLN_TClass;
extern G__linked_taginfo G__PIDTableDictLN_TBuffer;
extern G__linked_taginfo G__PIDTableDictLN_TMemberInspector;
extern G__linked_taginfo G__PIDTableDictLN_TObject;
extern G__linked_taginfo G__PIDTableDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PIDTableDictLN_TList;
extern G__linked_taginfo G__PIDTableDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__PIDTableDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PIDTableDictLN_TString;
extern G__linked_taginfo G__PIDTableDictLN_TF1;
extern G__linked_taginfo G__PIDTableDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__PIDTableDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PIDTableDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PIDTableDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PIDTableDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PIDTableDictLN_TH3D;
extern G__linked_taginfo G__PIDTableDictLN_PIDData;
extern G__linked_taginfo G__PIDTableDictLN_PIDTable;

/* STUB derived class for protected member access */
