//
// File generated by /afs/slac.stanford.edu/g/babar/package/root/5.14-00e/Linux24SL3_i386_gcc323/bin/rootcint at Tue Mar  2 05:31:24 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "recoilAnalysisDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void recoilAnalysis_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_recoilAnalysis(void *p = 0);
   static void *newArray_recoilAnalysis(Long_t size, void *p);
   static void delete_recoilAnalysis(void *p);
   static void deleteArray_recoilAnalysis(void *p);
   static void destruct_recoilAnalysis(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::recoilAnalysis*)
   {
      ::recoilAnalysis *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::recoilAnalysis >(0);
      static ::ROOT::TGenericClassInfo 
         instance("recoilAnalysis", ::recoilAnalysis::Class_Version(), "recoilAnalysis.hh", 21,
                  typeid(::recoilAnalysis), DefineBehavior(ptr, ptr),
                  &::recoilAnalysis::Dictionary, isa_proxy, 0,
                  sizeof(::recoilAnalysis) );
      instance.SetNew(&new_recoilAnalysis);
      instance.SetNewArray(&newArray_recoilAnalysis);
      instance.SetDelete(&delete_recoilAnalysis);
      instance.SetDeleteArray(&deleteArray_recoilAnalysis);
      instance.SetDestructor(&destruct_recoilAnalysis);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::recoilAnalysis*)
   {
      return GenerateInitInstanceLocal((::recoilAnalysis*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::recoilAnalysis*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *recoilAnalysis::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *recoilAnalysis::Class_Name()
{
   return "recoilAnalysis";
}

//______________________________________________________________________________
const char *recoilAnalysis::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::recoilAnalysis*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int recoilAnalysis::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::recoilAnalysis*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void recoilAnalysis::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::recoilAnalysis*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *recoilAnalysis::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::recoilAnalysis*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void recoilAnalysis::Streamer(TBuffer &R__b)
{
   // Stream an object of class recoilAnalysis.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b >> fNB;
      R__b >> fNBe;
      R__b >> fc;
      R__b >> fg;
      R__b >> fa;
      R__b >> fga;
      R__b >> fca;
      R__b >> f0;
      R__b >> f1;
      R__b >> f2;
      tl.Streamer(R__b);
      R__b >> fMesMinEvents;
      R__b >> nMc;
      R__b >> nDa;
      R__b >> nTs;
      R__b >> nTsc;
      int R__i;
      for (R__i = 0; R__i < 20; R__i++)
         R__b >> fMc[R__i];
      for (R__i = 0; R__i < 20; R__i++)
         R__b >> fDa[R__i];
      for (R__i = 0; R__i < 105; R__i++)
         R__b >> fTs[R__i];
      for (R__i = 0; R__i < 105; R__i++)
         R__b >> fTsc[R__i];
      R__b.ReadStaticArray((double*)fMcLumi);
      R__b.ReadStaticArray((double*)fDaLumi);
      R__b.ReadStaticArray((int*)fArplatC);
      R__b.ReadStaticArray((int*)fArlowC);
      R__b.ReadStaticArray((int*)fArupC);
      R__b.ReadStaticArray((int*)fArpartC);
      R__b.ReadStaticArray((char*)fArarrC);
      R__b.ReadStaticArray((char*)fArrunC);
      R__b.ReadStaticArray((double*)fArCand);
      R__b.ReadStaticArray((double*)fArCandC);
      R__b.ReadStaticArray((int*)fArplat);
      R__b.ReadStaticArray((int*)fArlow);
      R__b.ReadStaticArray((int*)fArup);
      R__b.ReadStaticArray((int*)fArpart);
      R__b.ReadStaticArray((char*)fArarr);
      R__b.ReadStaticArray((char*)fArrun);
      R__b.ReadStaticArray((int*)fflagC);
      R__b.ReadStaticArray((int*)fflag);
      R__b.ReadStaticArray((int*)fLines);
      R__b.ReadStaticArray((int*)fLinef);
      R__b.CheckByteCount(R__s, R__c, recoilAnalysis::IsA());
   } else {
      R__c = R__b.WriteVersion(recoilAnalysis::IsA(), kTRUE);
      R__b << fNB;
      R__b << fNBe;
      R__b << fc;
      R__b << fg;
      R__b << fa;
      R__b << fga;
      R__b << fca;
      R__b << f0;
      R__b << f1;
      R__b << f2;
      tl.Streamer(R__b);
      R__b << fMesMinEvents;
      R__b << nMc;
      R__b << nDa;
      R__b << nTs;
      R__b << nTsc;
      int R__i;
      for (R__i = 0; R__i < 20; R__i++)
         R__b << fMc[R__i];
      for (R__i = 0; R__i < 20; R__i++)
         R__b << fDa[R__i];
      for (R__i = 0; R__i < 105; R__i++)
         R__b << fTs[R__i];
      for (R__i = 0; R__i < 105; R__i++)
         R__b << fTsc[R__i];
      R__b.WriteArray(fMcLumi, 20);
      R__b.WriteArray(fDaLumi, 20);
      R__b.WriteArray(fArplatC, 12);
      R__b.WriteArray(fArlowC, 12);
      R__b.WriteArray(fArupC, 12);
      R__b.WriteArray(fArpartC, 12);
      R__b.WriteArray(fArarrC, 12);
      R__b.WriteArray((char*)fArrunC, 156);
      R__b.WriteArray(fArCand, 12);
      R__b.WriteArray(fArCandC, 12);
      R__b.WriteArray(fArplat, 12);
      R__b.WriteArray(fArlow, 12);
      R__b.WriteArray(fArup, 12);
      R__b.WriteArray(fArpart, 12);
      R__b.WriteArray(fArarr, 12);
      R__b.WriteArray((char*)fArrun, 156);
      R__b.WriteArray((int*)fflagC, 1260);
      R__b.WriteArray((int*)fflag, 1260);
      R__b.WriteArray(fLines, 105);
      R__b.WriteArray(fLinef, 105);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void recoilAnalysis::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class recoilAnalysis.
      TClass *R__cl = ::recoilAnalysis::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fNB", &fNB);
      R__insp.Inspect(R__cl, R__parent, "fNBe", &fNBe);
      R__insp.Inspect(R__cl, R__parent, "*fc", &fc);
      R__insp.Inspect(R__cl, R__parent, "*fg", &fg);
      R__insp.Inspect(R__cl, R__parent, "*fa", &fa);
      R__insp.Inspect(R__cl, R__parent, "*fga", &fga);
      R__insp.Inspect(R__cl, R__parent, "*fca", &fca);
      R__insp.Inspect(R__cl, R__parent, "*f0", &f0);
      R__insp.Inspect(R__cl, R__parent, "*f1", &f1);
      R__insp.Inspect(R__cl, R__parent, "*f2", &f2);
      R__insp.Inspect(R__cl, R__parent, "tl", &tl);
      tl.ShowMembers(R__insp, strcat(R__parent,"tl.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fMesMinEvents", &fMesMinEvents);
      R__insp.Inspect(R__cl, R__parent, "nMc", &nMc);
      R__insp.Inspect(R__cl, R__parent, "nDa", &nDa);
      R__insp.Inspect(R__cl, R__parent, "nTs", &nTs);
      R__insp.Inspect(R__cl, R__parent, "nTsc", &nTsc);
      R__insp.Inspect(R__cl, R__parent, "*fMc[20]", &fMc);
      R__insp.Inspect(R__cl, R__parent, "*fDa[20]", &fDa);
      R__insp.Inspect(R__cl, R__parent, "*fTs[105]", &fTs);
      R__insp.Inspect(R__cl, R__parent, "*fTsc[105]", &fTsc);
      R__insp.Inspect(R__cl, R__parent, "fMcLumi[20]", fMcLumi);
      R__insp.Inspect(R__cl, R__parent, "fDaLumi[20]", fDaLumi);
      R__insp.Inspect(R__cl, R__parent, "fArplatC[12]", fArplatC);
      R__insp.Inspect(R__cl, R__parent, "fArlowC[12]", fArlowC);
      R__insp.Inspect(R__cl, R__parent, "fArupC[12]", fArupC);
      R__insp.Inspect(R__cl, R__parent, "fArpartC[12]", fArpartC);
      R__insp.Inspect(R__cl, R__parent, "fArarrC[12]", fArarrC);
      R__insp.Inspect(R__cl, R__parent, "fArrunC[12][13]", fArrunC);
      R__insp.Inspect(R__cl, R__parent, "fArCand[12]", fArCand);
      R__insp.Inspect(R__cl, R__parent, "fArCandC[12]", fArCandC);
      R__insp.Inspect(R__cl, R__parent, "fArplat[12]", fArplat);
      R__insp.Inspect(R__cl, R__parent, "fArlow[12]", fArlow);
      R__insp.Inspect(R__cl, R__parent, "fArup[12]", fArup);
      R__insp.Inspect(R__cl, R__parent, "fArpart[12]", fArpart);
      R__insp.Inspect(R__cl, R__parent, "fArarr[12]", fArarr);
      R__insp.Inspect(R__cl, R__parent, "fArrun[12][13]", fArrun);
      R__insp.Inspect(R__cl, R__parent, "fflagC[12][105]", fflagC);
      R__insp.Inspect(R__cl, R__parent, "fflag[12][105]", fflag);
      R__insp.Inspect(R__cl, R__parent, "fLines[105]", fLines);
      R__insp.Inspect(R__cl, R__parent, "fLinef[105]", fLinef);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_recoilAnalysis(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::recoilAnalysis : new ::recoilAnalysis;
   }
   static void *newArray_recoilAnalysis(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::recoilAnalysis[nElements] : new ::recoilAnalysis[nElements];
   }
   // Wrapper around operator delete
   static void delete_recoilAnalysis(void *p) {
      delete ((::recoilAnalysis*)p);
   }
   static void deleteArray_recoilAnalysis(void *p) {
      delete [] ((::recoilAnalysis*)p);
   }
   static void destruct_recoilAnalysis(void *p) {
      typedef ::recoilAnalysis current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::recoilAnalysis

/********************************************************
* recoilAnalysisDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablerecoilAnalysisDict();

extern "C" void G__set_cpp_environmentrecoilAnalysisDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("mesData.hh");
  G__add_compiledheader("recoilAnalysis.hh");
  G__cpp_reset_tagtablerecoilAnalysisDict();
}
#include <new>
extern "C" int G__cpp_dllrevrecoilAnalysisDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* recoilAnalysis */
static int G__recoilAnalysisDict_285_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   recoilAnalysis* p = NULL;
   long gvp = G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilAnalysis[n];
     } else {
       p = new((void*) gvp) recoilAnalysis[n];
     }
   } else {
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilAnalysis;
     } else {
       p = new((void*) gvp) recoilAnalysis;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 8:
      ((recoilAnalysis*) G__getstructoffset())->setTitles(
(TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (int) G__int(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((recoilAnalysis*) G__getstructoffset())->setTitles(
(TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]));
      G__setnull(result7);
      break;
   case 6:
      ((recoilAnalysis*) G__getstructoffset())->setTitles((TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5]));
      G__setnull(result7);
      break;
   case 5:
      ((recoilAnalysis*) G__getstructoffset())->setTitles((TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((recoilAnalysis*) G__getstructoffset())->setTitles((TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((recoilAnalysis*) G__getstructoffset())->setTitles((TH1*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ((recoilAnalysis*) G__getstructoffset())->setHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (float) G__double(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((recoilAnalysis*) G__getstructoffset())->setHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((recoilAnalysis*) G__getstructoffset())->setHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->setHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->setHist((TH1*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ((recoilAnalysis*) G__getstructoffset())->setFilledHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((recoilAnalysis*) G__getstructoffset())->setFilledHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((recoilAnalysis*) G__getstructoffset())->setFilledHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->setFilledHist((TH1*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->setFilledHist((TH1*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadFiles((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadTimestamp((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadTimestampI((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadTimestampC((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->loadMc((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->loadMc((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->loadDa((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->loadDa((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadTs((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->loadTsC((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->lsMc();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->lsTs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->lsTsc();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->lsDa();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((recoilAnalysis*) G__getstructoffset())->eraser((char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (char*) G__int(libp->para[2]), (int) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((recoilAnalysis*) G__getstructoffset())->eraser((char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->eraser((char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->eraser((char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((recoilAnalysis*) G__getstructoffset())->eraser();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((recoilAnalysis*) G__getstructoffset())->Dump((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((recoilAnalysis*) G__getstructoffset())->Dump((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((recoilAnalysis*) G__getstructoffset())->Dump((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((recoilAnalysis*) G__getstructoffset())->dBinomial((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->mes((TH1D*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->mes((TH1D*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->newMes((TH1D*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->newMes((TH1D*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->newMes((TH1D*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 12:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])
, (double) G__double(libp->para[10]), (double) G__double(libp->para[11])));
      break;
   case 11:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])
, (double) G__double(libp->para[10])));
      break;
   case 10:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])));
      break;
   case 9:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8])));
      break;
   case 8:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (double) G__double(libp->para[7])));
      break;
   case 7:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes(
(TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6])));
      break;
   case 6:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes((TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), (int) G__int(libp->para[5])));
      break;
   case 5:
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->vubMes((TH1D*) G__int(libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->setMesMinimum((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((recoilAnalysis*) G__getstructoffset())->getMesMinimum());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->getMesFunction((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((recoilAnalysis*) G__getstructoffset())->getBgScale((TH1D*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->bgSubtracted((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->bgSubtracted((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((recoilAnalysis*) G__getstructoffset())->bgSubtracted((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((recoilAnalysis*) G__getstructoffset())->getNB());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) recoilAnalysis::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilAnalysis::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) recoilAnalysis::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      recoilAnalysis::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const recoilAnalysis*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilAnalysis*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilAnalysis::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) recoilAnalysis::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilAnalysis::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilAnalysisDict_285_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) recoilAnalysis::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__recoilAnalysisDict_285_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   recoilAnalysis* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new recoilAnalysis(*(recoilAnalysis*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef recoilAnalysis G__TrecoilAnalysis;
static int G__recoilAnalysisDict_285_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (recoilAnalysis*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((recoilAnalysis*) (soff+(sizeof(recoilAnalysis)*i)))->~G__TrecoilAnalysis();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (recoilAnalysis*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((recoilAnalysis*) (soff))->~G__TrecoilAnalysis();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* recoilAnalysis */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrecoilAnalysisDict {
 public:
  G__Sizep2memfuncrecoilAnalysisDict() {p=&G__Sizep2memfuncrecoilAnalysisDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrecoilAnalysisDict::*p)();
};

size_t G__get_sizep2memfuncrecoilAnalysisDict()
{
  G__Sizep2memfuncrecoilAnalysisDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerecoilAnalysisDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerecoilAnalysisDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,Version_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* recoilAnalysis */
static void G__setup_memvarrecoilAnalysis(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis));
   { recoilAnalysis *p; p=(recoilAnalysis*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,100,0,0,-1,-1,-1,4,"fNB=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,100,0,0,-1,-1,-1,4,"fNBe=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"fc=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"fg=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"fa=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"fga=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"fca=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"f0=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"f1=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1),-1,-1,4,"f2=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TLatex),-1,-1,4,"tl=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"fMesMinEvents=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nMc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nMc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nDa)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nDa=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nTs)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nTs=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nTsc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nTsc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fMc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TFile),-1,-1,1,"fMc[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fDa)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TFile),-1,-1,1,"fDa[20]=",0,"array for files ");
   G__memvar_setup((void*)((long)(&p->fTs)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TObjString),-1,-1,1,"fTs[105]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTsc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TObjString),-1,-1,1,"fTsc[105]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fMcLumi)-(long)(p)),100,0,0,-1,-1,-1,1,"fMcLumi[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fDaLumi)-(long)(p)),100,0,0,-1,-1,-1,1,"fDaLumi[20]=",0,"array with corresponding luminosities");
   G__memvar_setup((void*)((long)(&p->fArplatC)-(long)(p)),105,0,0,-1,-1,-1,1,"fArplatC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArlowC)-(long)(p)),105,0,0,-1,-1,-1,1,"fArlowC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArupC)-(long)(p)),105,0,0,-1,-1,-1,1,"fArupC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArpartC)-(long)(p)),105,0,0,-1,-1,-1,1,"fArpartC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArarrC)-(long)(p)),99,0,0,-1,-1,-1,1,"fArarrC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArrunC)-(long)(p)),99,0,0,-1,-1,-1,1,"fArrunC[12][13]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArCand)-(long)(p)),100,0,0,-1,-1,-1,1,"fArCand[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArCandC)-(long)(p)),100,0,0,-1,-1,-1,1,"fArCandC[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArplat)-(long)(p)),105,0,0,-1,-1,-1,1,"fArplat[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArlow)-(long)(p)),105,0,0,-1,-1,-1,1,"fArlow[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArup)-(long)(p)),105,0,0,-1,-1,-1,1,"fArup[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArpart)-(long)(p)),105,0,0,-1,-1,-1,1,"fArpart[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArarr)-(long)(p)),99,0,0,-1,-1,-1,1,"fArarr[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fArrun)-(long)(p)),99,0,0,-1,-1,-1,1,"fArrun[12][13]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fflagC)-(long)(p)),105,0,0,-1,-1,-1,1,"fflagC[12][105]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fflag)-(long)(p)),105,0,0,-1,-1,-1,1,"fflag[12][105]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fLines)-(long)(p)),105,0,0,-1,-1,-1,1,"fLines[105]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fLinef)-(long)(p)),105,0,0,-1,-1,-1,1,"fLinef[105]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilAnalysisDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrecoilAnalysisDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncrecoilAnalysis(void) {
   /* recoilAnalysis */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis));
   G__memfunc_setup("recoilAnalysis",1474,G__recoilAnalysisDict_285_0_1, 105, G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTitles",961,G__recoilAnalysisDict_285_0_2, 121, -1, -1, 0, 8, 1, 1, 0, 
"U 'TH1' - 0 - h C - - 10 - sx "
"C - - 10 - sy f - - 0 0.05 size "
"f - - 0 1.1 xoff f - - 0 1.0 yoff "
"f - - 0 0.05 lsize i - - 0 62 font", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setHist",740,G__recoilAnalysisDict_285_0_3, 121, -1, -1, 0, 5, 1, 1, 0, 
"U 'TH1' - 0 - h i - - 0 1 color "
"i - - 0 20 symbol f - - 0 1. size "
"i - - 0 2 width", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFilledHist",1332,G__recoilAnalysisDict_285_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"U 'TH1' - 0 - h i - - 0 1 color "
"i - - 0 1 fillcolor i - - 0 3004 fillstyle "
"i - - 0 1 width", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadFiles",915,G__recoilAnalysisDict_285_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadTimestamp",1364,G__recoilAnalysisDict_285_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadTimestampI",1437,G__recoilAnalysisDict_285_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadTimestampC",1431,G__recoilAnalysisDict_285_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadMc",592,G__recoilAnalysisDict_285_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - name d - - 0 -1. lumi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadDa",581,G__recoilAnalysisDict_285_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - name d - - 0 -1. lumi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadTs",615,G__recoilAnalysisDict_285_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadTsC",682,G__recoilAnalysisDict_285_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lsMc",399,G__recoilAnalysisDict_285_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lsTs",422,G__recoilAnalysisDict_285_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lsTsc",521,G__recoilAnalysisDict_285_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lsDa",388,G__recoilAnalysisDict_285_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eraser",642,G__recoilAnalysisDict_285_0_17, 121, -1, -1, 0, 4, 1, 1, 0, 
"C - - 0 0 fileI i - - 0 0 inf "
"C - - 0 0 fileC i - - 0 0 infC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Dump",406,G__recoilAnalysisDict_285_0_18, 121, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - filename i - - 0 -1 fi "
"i - - 0 -1 fiC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dBinomial",911,G__recoilAnalysisDict_285_0_19, 100, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("mes",325,G__recoilAnalysisDict_285_0_20, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_mesData), -1, 0, 2, 1, 1, 0, 
"U 'TH1D' - 0 - h i - - 0 1 print", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("newMes",623,G__recoilAnalysisDict_285_0_21, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_mesData), -1, 0, 3, 1, 1, 0, 
"U 'TH1D' - 0 - h i - - 0 1 print "
"i - - 0 0 func", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vubMes",626,G__recoilAnalysisDict_285_0_22, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_mesData), -1, 0, 12, 1, 1, 0, 
"U 'TH1D' - 0 - h d - - 1 - resmean "
"d - - 1 - ressigma d - - 1 - resalpha "
"d - - 1 - resn i - - 0 1 print "
"i - - 0 0 func d - - 0 0 mean "
"d - - 0 0 sigma d - - 0 0 alpha "
"d - - 0 0 n d - - 0 0 argus", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMesMinimum",1357,G__recoilAnalysisDict_285_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getMesMinimum",1345,G__recoilAnalysisDict_285_0_24, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getMesFunction",1451,G__recoilAnalysisDict_285_0_25, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBgScale",977,G__recoilAnalysisDict_285_0_26, 100, -1, -1, 0, 1, 1, 1, 0, "U 'TH1D' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bgSubtracted",1242,G__recoilAnalysisDict_285_0_27, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TH1D), -1, 0, 2, 1, 1, 0, 
"C - - 10 - hist C - - 10 - dir", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bgSubtracted",1242,G__recoilAnalysisDict_285_0_28, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TH1D), -1, 0, 3, 1, 1, 0, 
"C - - 10 - hist C - - 10 - dir "
"C - - 10 - subdir", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bgSubtracted",1242,G__recoilAnalysisDict_285_0_29, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TH1D), -1, 0, 4, 1, 1, 0, 
"C - - 10 - hist C - - 10 - dir "
"C - - 10 - postfix i - - 0 - func", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNB",464,G__recoilAnalysisDict_285_0_30, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__recoilAnalysisDict_285_0_31, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&recoilAnalysis::Class), 0);
   G__memfunc_setup("Class_Name",982,G__recoilAnalysisDict_285_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilAnalysis::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__recoilAnalysisDict_285_0_33, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&recoilAnalysis::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__recoilAnalysisDict_285_0_34, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&recoilAnalysis::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__recoilAnalysisDict_285_0_35, 85, G__get_linked_tagnum(&G__recoilAnalysisDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__recoilAnalysisDict_285_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__recoilAnalysisDict_285_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__recoilAnalysisDict_285_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__recoilAnalysisDict_285_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilAnalysis::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__recoilAnalysisDict_285_0_40, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&recoilAnalysis::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__recoilAnalysisDict_285_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilAnalysis::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__recoilAnalysisDict_285_0_42, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&recoilAnalysis::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("recoilAnalysis", 1474, G__recoilAnalysisDict_285_0_43, (int) ('i'), G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis), -1, 0, 1, 1, 1, 0, "u 'recoilAnalysis' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~recoilAnalysis", 1600, G__recoilAnalysisDict_285_0_44, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrecoilAnalysisDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrecoilAnalysisDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrecoilAnalysisDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__recoilAnalysisDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_mesData = { "mesData" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "multimap<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TObjString = { "TObjString" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_TLatex = { "TLatex" , 99 , -1 };
G__linked_taginfo G__recoilAnalysisDictLN_recoilAnalysis = { "recoilAnalysis" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerecoilAnalysisDict() {
  G__recoilAnalysisDictLN_TClass.tagnum = -1 ;
  G__recoilAnalysisDictLN_TBuffer.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMemberInspector.tagnum = -1 ;
  G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TFile.tagnum = -1 ;
  G__recoilAnalysisDictLN_mesData.tagnum = -1 ;
  G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__recoilAnalysisDictLN_TH1.tagnum = -1 ;
  G__recoilAnalysisDictLN_TF1.tagnum = -1 ;
  G__recoilAnalysisDictLN_TH1D.tagnum = -1 ;
  G__recoilAnalysisDictLN_TObjString.tagnum = -1 ;
  G__recoilAnalysisDictLN_TLatex.tagnum = -1 ;
  G__recoilAnalysisDictLN_recoilAnalysis.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerecoilAnalysisDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TClass);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TBuffer);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TFile);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_mesData);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TH1);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TF1);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TH1D);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TObjString);
   G__get_linked_tagnum(&G__recoilAnalysisDictLN_TLatex);
   G__tagtable_setup(G__get_linked_tagnum(&G__recoilAnalysisDictLN_recoilAnalysis),sizeof(recoilAnalysis),-1,1280,(char*)NULL,G__setup_memvarrecoilAnalysis,G__setup_memfuncrecoilAnalysis);
}
extern "C" void G__cpp_setuprecoilAnalysisDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprecoilAnalysisDict()");
  G__set_cpp_environmentrecoilAnalysisDict();
  G__cpp_setup_tagtablerecoilAnalysisDict();

  G__cpp_setup_inheritancerecoilAnalysisDict();

  G__cpp_setup_typetablerecoilAnalysisDict();

  G__cpp_setup_memvarrecoilAnalysisDict();

  G__cpp_setup_memfuncrecoilAnalysisDict();
  G__cpp_setup_globalrecoilAnalysisDict();
  G__cpp_setup_funcrecoilAnalysisDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrecoilAnalysisDict();
  return;
}
class G__cpp_setup_initrecoilAnalysisDict {
  public:
    G__cpp_setup_initrecoilAnalysisDict() { G__add_setup_func("recoilAnalysisDict",(G__incsetup)(&G__cpp_setuprecoilAnalysisDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrecoilAnalysisDict() { G__remove_setup_func("recoilAnalysisDict"); }
};
G__cpp_setup_initrecoilAnalysisDict G__cpp_setup_initializerrecoilAnalysisDict;

