//
// File generated by /afs/slac.stanford.edu/g/babar/package/root/5.14-00e/Linux24SL3_i386_gcc323/bin/rootcint at Tue Mar  2 05:31:38 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "recoilDSysDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void recoilDSys_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_recoilDSys(void *p = 0);
   static void *newArray_recoilDSys(Long_t size, void *p);
   static void delete_recoilDSys(void *p);
   static void deleteArray_recoilDSys(void *p);
   static void destruct_recoilDSys(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::recoilDSys*)
   {
      ::recoilDSys *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::recoilDSys >(0);
      static ::ROOT::TGenericClassInfo 
         instance("recoilDSys", ::recoilDSys::Class_Version(), "recoilDSys.hh", 20,
                  typeid(::recoilDSys), DefineBehavior(ptr, ptr),
                  &::recoilDSys::Dictionary, isa_proxy, 0,
                  sizeof(::recoilDSys) );
      instance.SetNew(&new_recoilDSys);
      instance.SetNewArray(&newArray_recoilDSys);
      instance.SetDelete(&delete_recoilDSys);
      instance.SetDeleteArray(&deleteArray_recoilDSys);
      instance.SetDestructor(&destruct_recoilDSys);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::recoilDSys*)
   {
      return GenerateInitInstanceLocal((::recoilDSys*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::recoilDSys*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *recoilDSys::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *recoilDSys::Class_Name()
{
   return "recoilDSys";
}

//______________________________________________________________________________
const char *recoilDSys::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::recoilDSys*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int recoilDSys::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::recoilDSys*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void recoilDSys::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::recoilDSys*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *recoilDSys::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::recoilDSys*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void recoilDSys::Streamer(TBuffer &R__b)
{
   // Stream an object of class recoilDSys.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b.ReadStaticArray((int*)_nPiMode);
      R__b.ReadStaticArray((int*)_nKMode);
      R__b.ReadStaticArray((int*)_nK0Mode);
      R__b.ReadStaticArray((int*)_nPi0Mode);
      R__b.ReadStaticArray((float*)_weightMode);
      R__b >> _nmodes;
      R__b.ReadStaticArray((float*)_b0weights);
      R__b.ReadStaticArray((float*)_bchweights);
      R__b >> _b0WeightsAllSemilep;
      R__b >> _bchWeightsAllSemilep;
      R__b.CheckByteCount(R__s, R__c, recoilDSys::IsA());
   } else {
      R__c = R__b.WriteVersion(recoilDSys::IsA(), kTRUE);
      R__b.WriteArray(_nPiMode, 100);
      R__b.WriteArray(_nKMode, 100);
      R__b.WriteArray(_nK0Mode, 100);
      R__b.WriteArray(_nPi0Mode, 100);
      R__b.WriteArray(_weightMode, 100);
      R__b << _nmodes;
      R__b.WriteArray(_b0weights, 6);
      R__b.WriteArray(_bchweights, 6);
      R__b << _b0WeightsAllSemilep;
      R__b << _bchWeightsAllSemilep;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void recoilDSys::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class recoilDSys.
      TClass *R__cl = ::recoilDSys::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "_nPiMode[100]", _nPiMode);
      R__insp.Inspect(R__cl, R__parent, "_nKMode[100]", _nKMode);
      R__insp.Inspect(R__cl, R__parent, "_nK0Mode[100]", _nK0Mode);
      R__insp.Inspect(R__cl, R__parent, "_nPi0Mode[100]", _nPi0Mode);
      R__insp.Inspect(R__cl, R__parent, "_weightMode[100]", _weightMode);
      R__insp.Inspect(R__cl, R__parent, "_nmodes", &_nmodes);
      R__insp.Inspect(R__cl, R__parent, "_b0weights[6]", _b0weights);
      R__insp.Inspect(R__cl, R__parent, "_bchweights[6]", _bchweights);
      R__insp.Inspect(R__cl, R__parent, "_b0WeightsAllSemilep", &_b0WeightsAllSemilep);
      R__insp.Inspect(R__cl, R__parent, "_bchWeightsAllSemilep", &_bchWeightsAllSemilep);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_recoilDSys(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::recoilDSys : new ::recoilDSys;
   }
   static void *newArray_recoilDSys(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::recoilDSys[nElements] : new ::recoilDSys[nElements];
   }
   // Wrapper around operator delete
   static void delete_recoilDSys(void *p) {
      delete ((::recoilDSys*)p);
   }
   static void deleteArray_recoilDSys(void *p) {
      delete [] ((::recoilDSys*)p);
   }
   static void destruct_recoilDSys(void *p) {
      typedef ::recoilDSys current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::recoilDSys

/********************************************************
* recoilDSysDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablerecoilDSysDict();

extern "C" void G__set_cpp_environmentrecoilDSysDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("recoilDSys.hh");
  G__cpp_reset_tagtablerecoilDSysDict();
}
#include <new>
extern "C" int G__cpp_dllrevrecoilDSysDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* recoilDSys */
static int G__recoilDSysDict_285_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   recoilDSys* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys(
(const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) recoilDSys(
(const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) recoilDSys((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) recoilDSys((const char*) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   recoilDSys* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) recoilDSys(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) recoilDSys((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new recoilDSys((int) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) recoilDSys((int) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new recoilDSys[n];
       } else {
         p = new((void*) gvp) recoilDSys[n];
       }
     } else {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new recoilDSys;
       } else {
         p = new((void*) gvp) recoilDSys;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((recoilDSys*) G__getstructoffset())->recoilDSys2((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((recoilDSys*) G__getstructoffset())->recoilDSys2();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((recoilDSys*) G__getstructoffset())->recoilDSys3((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((recoilDSys*) G__getstructoffset())->recoilDSys3();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((recoilDSys*) G__getstructoffset())->weight(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, *(int*) G__Intref(&libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((recoilDSys*) G__getstructoffset())->weight((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((recoilDSys*) G__getstructoffset())->getAllSemilepWeight((bool) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilDSys*) G__getstructoffset())->reweightForSys((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) recoilDSys::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilDSys::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) recoilDSys::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      recoilDSys::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const recoilDSys*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilDSys*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilDSys*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((recoilDSys*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilDSys::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) recoilDSys::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) recoilDSys::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__recoilDSysDict_285_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) recoilDSys::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__recoilDSysDict_285_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   recoilDSys* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new recoilDSys(*(recoilDSys*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef recoilDSys G__TrecoilDSys;
static int G__recoilDSysDict_285_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (recoilDSys*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((recoilDSys*) (soff+(sizeof(recoilDSys)*i)))->~G__TrecoilDSys();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (recoilDSys*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((recoilDSys*) (soff))->~G__TrecoilDSys();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__recoilDSysDict_285_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   recoilDSys* dest = (recoilDSys*) G__getstructoffset();
   *dest = *(recoilDSys*) libp->para[0].ref;
   const recoilDSys& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* recoilDSys */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrecoilDSysDict {
 public:
  G__Sizep2memfuncrecoilDSysDict() {p=&G__Sizep2memfuncrecoilDSysDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrecoilDSysDict::*p)();
};

size_t G__get_sizep2memfuncrecoilDSysDict()
{
  G__Sizep2memfuncrecoilDSysDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerecoilDSysDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerecoilDSysDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,Version_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__recoilDSysDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* recoilDSys */
static void G__setup_memvarrecoilDSys(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys));
   { recoilDSys *p; p=(recoilDSys*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"_nPiMode[100]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"_nKMode[100]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"_nK0Mode[100]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"_nPi0Mode[100]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,102,0,0,-1,-1,-1,4,"_weightMode[100]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"_nmodes=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,102,0,0,-1,-1,-1,4,"_b0weights[6]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,102,0,0,-1,-1,-1,4,"_bchweights[6]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,102,0,0,-1,-1,-1,4,"_b0WeightsAllSemilep=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,102,0,0,-1,-1,-1,4,"_bchWeightsAllSemilep=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__recoilDSysDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrecoilDSysDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncrecoilDSys(void) {
   /* recoilDSys */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys));
   G__memfunc_setup("readFile",796,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"C - - 10 - InputFileName i - - 0 0 seed "
"i - - 0 0 iMode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("randomized",1069,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 4, 1, 4, 0, 
"f - - 0 - mean f - - 0 - sig "
"u 'TRandom' - 1 - rndm i - - 0 - seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Brandomized",1135,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 5, 1, 4, 0, 
"f - - 0 - mean f - - 0 - lsig "
"f - - 0 - hsig u 'TRandom' - 1 - rndm "
"i - - 0 - seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("recoilDSys",1025,G__recoilDSysDict_285_0_4, 105, G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys), -1, 0, 3, 1, 1, 0, 
"C - - 10 - InputFileName i - - 0 0 seed "
"i - - 0 0 imode", "constructor for D decays (list from file)", (void*) NULL, 0);
   G__memfunc_setup("recoilDSys",1025,G__recoilDSysDict_285_0_5, 105, G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys), -1, 0, 3, 1, 1, 0, 
"i - - 0 0 seed i - - 0 14 rel "
"i - - 0 -99 sysbdec", "constructor for B->Dlnu decays (numbers hard coded for rel 14 (effectively SP4, SP5/SP6) and rel 18 (effectively SP8)", (void*) NULL, 0);
   G__memfunc_setup("recoilDSys2",1075,G__recoilDSysDict_285_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 0 num", "Fake constructor for B->Dlnu decays (read weights from file)", (void*) NULL, 0);
   G__memfunc_setup("recoilDSys3",1076,G__recoilDSysDict_285_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 0 num", "Fake constructor for D decays (read weights from file)", (void*) NULL, 0);
   G__memfunc_setup("weight",648,G__recoilDSysDict_285_0_8, 102, -1, -1, 0, 7, 1, 1, 0, 
"i - - 0 - npi i - - 0 - nk "
"i - - 0 - nk0 i - - 0 - npi0 "
"i - - 0 - nlep i - - 0 - imOde "
"i - - 1 - mode", "for D decays  ", (void*) NULL, 0);
   G__memfunc_setup("weight",648,G__recoilDSysDict_285_0_9, 102, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - bdecay", "for B decays", (void*) NULL, 0);
   G__memfunc_setup("getAllSemilepWeight",1936,G__recoilDSysDict_285_0_10, 102, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", "to get the first weight.", (void*) NULL, 0);
   G__memfunc_setup("reweightForSys",1477,G__recoilDSysDict_285_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", "Recomputes weight for B->Dlv systematic studies", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__recoilDSysDict_285_0_12, 85, G__get_linked_tagnum(&G__recoilDSysDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&recoilDSys::Class), 0);
   G__memfunc_setup("Class_Name",982,G__recoilDSysDict_285_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilDSys::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__recoilDSysDict_285_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&recoilDSys::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__recoilDSysDict_285_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&recoilDSys::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__recoilDSysDict_285_0_16, 85, G__get_linked_tagnum(&G__recoilDSysDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__recoilDSysDict_285_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__recoilDSysDict_285_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__recoilDSysDict_285_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__recoilDSysDict_285_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilDSys::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__recoilDSysDict_285_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&recoilDSys::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__recoilDSysDict_285_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&recoilDSys::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__recoilDSysDict_285_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&recoilDSys::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("recoilDSys", 1025, G__recoilDSysDict_285_0_24, (int) ('i'), G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys), -1, 0, 1, 1, 1, 0, "u 'recoilDSys' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~recoilDSys", 1151, G__recoilDSysDict_285_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__recoilDSysDict_285_0_26, (int) ('u'), G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys), -1, 1, 1, 1, 1, 0, "u 'recoilDSys' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrecoilDSysDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrecoilDSysDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrecoilDSysDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__recoilDSysDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "multimap<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_TRandom = { "TRandom" , 99 , -1 };
G__linked_taginfo G__recoilDSysDictLN_recoilDSys = { "recoilDSys" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerecoilDSysDict() {
  G__recoilDSysDictLN_TClass.tagnum = -1 ;
  G__recoilDSysDictLN_TBuffer.tagnum = -1 ;
  G__recoilDSysDictLN_TMemberInspector.tagnum = -1 ;
  G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__recoilDSysDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__recoilDSysDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__recoilDSysDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__recoilDSysDictLN_TRandom.tagnum = -1 ;
  G__recoilDSysDictLN_recoilDSys.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerecoilDSysDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__recoilDSysDictLN_TClass);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TBuffer);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__recoilDSysDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum(&G__recoilDSysDictLN_TRandom);
   G__tagtable_setup(G__get_linked_tagnum(&G__recoilDSysDictLN_recoilDSys),sizeof(recoilDSys),-1,34048,(char*)NULL,G__setup_memvarrecoilDSys,G__setup_memfuncrecoilDSys);
}
extern "C" void G__cpp_setuprecoilDSysDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprecoilDSysDict()");
  G__set_cpp_environmentrecoilDSysDict();
  G__cpp_setup_tagtablerecoilDSysDict();

  G__cpp_setup_inheritancerecoilDSysDict();

  G__cpp_setup_typetablerecoilDSysDict();

  G__cpp_setup_memvarrecoilDSysDict();

  G__cpp_setup_memfuncrecoilDSysDict();
  G__cpp_setup_globalrecoilDSysDict();
  G__cpp_setup_funcrecoilDSysDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrecoilDSysDict();
  return;
}
class G__cpp_setup_initrecoilDSysDict {
  public:
    G__cpp_setup_initrecoilDSysDict() { G__add_setup_func("recoilDSysDict",(G__incsetup)(&G__cpp_setuprecoilDSysDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrecoilDSysDict() { G__remove_setup_func("recoilDSysDict"); }
};
G__cpp_setup_initrecoilDSysDict G__cpp_setup_initializerrecoilDSysDict;

