/********************************************************************
* TRKDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TRKDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTRKDataDict();
extern void G__cpp_setup_inheritanceTRKDataDict();
extern void G__cpp_setup_typetableTRKDataDict();
extern void G__cpp_setup_memvarTRKDataDict();
extern void G__cpp_setup_globalTRKDataDict();
extern void G__cpp_setup_memfuncTRKDataDict();
extern void G__cpp_setup_funcTRKDataDict();
extern void G__set_cpp_environmentTRKDataDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TRKData.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRKDataDictLN_TClass;
extern G__linked_taginfo G__TRKDataDictLN_TBuffer;
extern G__linked_taginfo G__TRKDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TRKDataDictLN_TObject;
extern G__linked_taginfo G__TRKDataDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TRKDataDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRKDataDictLN_TRKData;

/* STUB derived class for protected member access */
