/********************************************************************
* TRKTableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TRKTableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTRKTableDict();
extern void G__cpp_setup_inheritanceTRKTableDict();
extern void G__cpp_setup_typetableTRKTableDict();
extern void G__cpp_setup_memvarTRKTableDict();
extern void G__cpp_setup_globalTRKTableDict();
extern void G__cpp_setup_memfuncTRKTableDict();
extern void G__cpp_setup_funcTRKTableDict();
extern void G__set_cpp_environmentTRKTableDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TRKTable.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TRKTableDictLN_TClass;
extern G__linked_taginfo G__TRKTableDictLN_TBuffer;
extern G__linked_taginfo G__TRKTableDictLN_TMemberInspector;
extern G__linked_taginfo G__TRKTableDictLN_TObject;
extern G__linked_taginfo G__TRKTableDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TRKTableDictLN_TList;
extern G__linked_taginfo G__TRKTableDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TRKTableDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TRKTableDictLN_TString;
extern G__linked_taginfo G__TRKTableDictLN_TF1;
extern G__linked_taginfo G__TRKTableDictLN_TRKData;
extern G__linked_taginfo G__TRKTableDictLN_TRKTable;

/* STUB derived class for protected member access */
